sudo: false 

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

before_deploy: 
  # Decrypt the deployment key
  - >-
    openssl aes-256-cbc -K $encrypted_7785451d7016_key \
      -iv $encrypted_7785451d7016_iv \
      -in '.ci/travis_deploy_key.enc' \
      -out 'travis_deploy_key' -d
      
deploy:
  # opt-in to dpl v2
  edge: true
  provider: pages:git
  deploy_key: travis_deploy_key
  cleanup: false
  keep_history: false
  local_dir: doc/html
  on:
    branch: master
