sudo: false 

branches:
  only:
    - master
    - Feature/XBCLIB-29-autodeploy-docs-to-github

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

before_deploy: 
  # Decrypt the deployment key
  - >-
    openssl aes-256-cbc -K $encrypted_7785451d7016_key \
      -iv $encrypted_7785451d7016_iv \
      -in '.ci/travis_deploy_key.enc' \
      -out 'travis_deploy_key' -d
      
deploy:
  provider: pages
  deploy_key: travis_deploy_key
  skip_cleanup: true
  local_dir: doc/html
  edge: true
  on:
    branch: master
