XBee/ZigBee Driver: Cluster/Endpoint layer
Cluster/Endpoint layer
Wireless Personal Area Networking (WPAN)
Files
file wpan_aps.c
Base WPAN/ZigBee layer, responsible for endpoints and clusters.
file aps.h
Cluster/Endpoint layer for WPAN networks (ZigBee and DigiMesh).
Data Structures
struct wpan_envelope_t
The "envelope" is used to gather all necessary information about a given frame on the network.
struct wpan_cluster_table_entry_t
Information on each cluster associated with an endpoint.
struct wpan_endpoint_table_entry_t
Information on each endpoint on this device.
struct wpan_dev_t
Structure used by the WPAN/ZigBee layers.
struct wpan_conversation_t
Used to track conversations (outstanding requests) on an endpoint.
struct wpan_ep_state_t
Volatile part of an endpoint record used to track conversations (requests waiting for responses).
Macros
#define wpan_aps_debug
#define WPAN_ENVELOPE_CLUSTER_FLAGS 0x00FF
mask of WPAN_CLUST_FLAG_* flags for the cluster tied to this envelope
#define WPAN_ENVELOPE_BROADCAST_ADDR 0x0100
frame was received on a broadcast address
#define WPAN_ENVELOPE_BROADCAST_EP 0x0200
frame was received on the broadcast endpoint (0xFF)
#define WPAN_ENVELOPE_RX_APS_ENCRYPT 0x0400
frame was received with APS encryption
#define WPAN_CLUSTER_END_OF_LIST 0xFFFF
Cluster ID used to mark the end of cluster_table in wpan_endpoint_table_entry_t.
#define WPAN_CLUST_ENTRY_LIST_END { WPAN_CLUSTER_END_OF_LIST }
Macro for a wpan_cluster_table_entry_t that can be used to mark the end of the table.
#define WPAN_FLAG_NONE 0x0000
#define WPAN_FLAG_JOINED 0x0001
device has joined a network (but not necessarily authenticated)
#define WPAN_FLAG_AUTHENTICATED 0x0002
device completed Key Establishment and can send APS encrypted frames
#define WPAN_FLAG_AUTHENTICATION_ENABLED 0x0004
device has encryption enabled (EO non-zero)
#define WPAN_DEV_IS_JOINED(dev) ((dev)->flags & WPAN_FLAG_JOINED)
Macro to test whether a device has joined the network.
#define WPAN_DEV_IS_AUTHENTICATED(dev) ((dev)->flags & WPAN_FLAG_AUTHENTICATED)
Macro to test whether a device has authenticated with the trust center.
#define WPAN_ENDPOINT_END_OF_LIST 0xFF
Endpoint ID used to mark the end of endpoint_table in wpan_dev_t.
#define WPAN_ENDPOINT_TABLE_END { WPAN_ENDPOINT_END_OF_LIST }
Macro for a wpan_endpoint_table_entry_t that can be used to mark the end of the table.
#define WPAN_APS_PROFILE_ANY 0xFFFF
#define WPAN_CONVERSATION_END 1
#define WPAN_CONVERSATION_CONTINUE 2
#define WPAN_MAX_CONVERSATIONS 3
Number of outstanding requests to track in a wpan_ep_state_t associated with an endpoint.
#define WPAN_CONVERSATION_TIMEOUT 30
Default conversation recycle timeout (seconds)
Typedefs
typedef int(* wpan_aps_handler_fn) (const wpan_envelope_t FAR *envelope, void FAR *context)
General handler used in the cluster table.
typedef int(* wpan_ep_handler_fn) (const wpan_envelope_t FAR *envelope, struct wpan_ep_state_t FAR *ep_state)
General handler used in the endpoint table.
typedef int(* wpan_endpoint_send_fn) (const wpan_envelope_t FAR *envelope, uint16_t flags)
Function called by the WPAN APS layer to send a frame out on the network.
typedef int(* _wpan_config_fn) (struct wpan_dev_t *dev,...)
Function called by the WPAN APS layer to configure the underlying network device.
typedef int(* wpan_tick_fn) (struct wpan_dev_t *dev)
Function called by the WPAN APS layer to have the underlying device read and dispatch frames.
typedef const wpan_endpoint_table_entry_t *(* wpan_endpoint_get_next_fn) (struct wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep)
Custom function for walking the endpoint table.
typedef int(* wpan_response_fn) (struct wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Handler registered with wpan_conversation_register() to process responses to outstanding requests.
Enumerations
enum wpan_clust_digi {
DIGI_CLUST_SLEEP_SYNC = 0x0009, DIGI_CLUST_SERIAL = 0x0011, DIGI_CLUST_LOOPBACK = 0x0012, DIGI_CLUST_ND_COMMAND = 0x0015,
DIGI_CLUST_DN_COMMAND = 0x0016, DIGI_CLUST_REMOTE_COMMAND = 0x0021, DIGI_CLUST_NR_COMMAND = 0x0022, DIGI_CLUST_IODATA = 0x0092,
DIGI_CLUST_WATCHPORT = 0x0094, DIGI_CLUST_NODEID_MESSAGE = 0x0095, DIGI_CLUST_DN_RESPONSE = 0x0096, DIGI_CLUST_REMOTE_RESPONSE = 0x00A1,
DIGI_CLUST_NR_RESPONSE = 0x00A2, DIGI_CLUST_INDIRECT_ROUTE_ERR = 0x00B0, DIGI_CLUST_PROG_XBEE_OTA_UPD = 0x1000, DIGI_CLUST_NBRFWUPDATE = 0x71FE,
DIGI_CLUST_REMFWUPDATE = 0x71FF, DIGI_CLUST_FWUPDATERESP = (int)0xF1FF
}
Digi Data cluster IDs (endpoint WPAN_ENDPOINT_DIGI_DATA)
Functions
const wpan_cluster_table_entry_t * wpan_cluster_match (uint16_t match, uint8_t mask, const wpan_cluster_table_entry_t *entry)
Search a cluster table for a matching cluster ID.
const wpan_endpoint_table_entry_t * wpan_endpoint_get_next (wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep)
Function used to walk a device's endpoint table.
const wpan_endpoint_table_entry_t * wpan_endpoint_match (wpan_dev_t *dev, uint8_t endpoint, uint16_t profile_id)
Walk a device's endpoint table looking for a matching endpoint ID and profile ID.
const wpan_endpoint_table_entry_t * wpan_endpoint_of_envelope (const wpan_envelope_t *env)
Look up the endpoint table entry for the source endpoint of an envelope.
const wpan_endpoint_table_entry_t * wpan_endpoint_of_cluster (wpan_dev_t *dev, uint16_t profile_id, uint16_t cluster_id, uint8_t mask)
Walk a device's endpoint table looking for a matching profile ID and cluster ID.
int wpan_conversation_register (wpan_ep_state_t FAR *state, wpan_response_fn handler, const void FAR *context, uint16_t timeout)
Add a conversation to the table of tracked conversations.
void wpan_conversation_delete (wpan_conversation_t FAR *conversation)
Delete a conversation from an endpoint's conversation table.
void _wpan_endpoint_expire_conversations (wpan_ep_state_t FAR *state)
Walk an endpoint's conversation table and expire any conversations that have timed out.
int wpan_conversation_response (wpan_ep_state_t FAR *state, uint8_t transaction_id, const wpan_envelope_t FAR *envelope)
Searches the endpoint's table of active conversations (outstanding requests waiting for responses) for a given transaction.
uint8_t wpan_endpoint_next_trans (const wpan_endpoint_table_entry_t *ep)
Increment and return the endpoint's transaction ID counter.
int _wpan_endpoint_dispatch (wpan_envelope_t *envelope, const wpan_endpoint_table_entry_t *ep)
Dispatch a message for a given endpoint.
int wpan_envelope_dispatch (wpan_envelope_t *envelope)
Find the matching endpoint for the provided envelope and have it process the frame.
void wpan_envelope_create (wpan_envelope_t *envelope, wpan_dev_t *dev, const addr64 FAR *ieee, uint16_t network_addr)
Starting with a blank envelope, fill in the device, 64-bit IEEE address and 16-bit network address of the destination.
int wpan_envelope_reply (wpan_envelope_t FAR *reply, const wpan_envelope_t FAR *original)
Create a reply envelope based on the envelope received from a remote node.
int wpan_envelope_send (const wpan_envelope_t FAR *envelope)
Send a message to an endpoint using address and payload information stored in a wpan_envelope_t structure.
void wpan_envelope_dump (const wpan_envelope_t FAR *envelope)
Debugging function to dump the contents of an envelope to stdout.
int wpan_tick (wpan_dev_t *dev)
Calls the underlying hardware tick function to process received frames, and times out expired conversations.
Variables
struct wpan_dev_t * dev
interface received on/to send to
addr64 ieee_address
remote 64-bit address
uint16_t network_address
remote 16-bit address
uint16_t profile_id
Profile ID.
uint16_t cluster_id
Cluster ID.
uint8_t source_endpoint
endpoint on sender (source)
uint8_t dest_endpoint
endpoint on recipient (dest)
uint16_t options
const void FAR * payload
contents of message
uint16_t length
number of bytes in payload
uint16_t cluster_id
16-bit cluster id, in host byte order.
wpan_aps_handler_fn handler
Function to receive all frames for this cluster, or NULL to have endpoint's handler process the frame.
const void FAR * context
Declared const so initializers can use const or non-const pointers.
uint8_t flags
flags that apply to this cluster, see WPAN_CLUST_FLAG_* macros
uint8_t endpoint
Endpoint ID, 0 to 254. 255 (0xFF) is used as an end-of-table marker.
uint16_t profile_id
This endpoint's profile ID.
wpan_ep_handler_fn handler
Function to receive all frames for invalid clusters, or clusters with a NULL handler.
struct wpan_ep_state_t FAR * ep_state
Structure used to track transactions and conversations on ZDO/ZDP and ZCL endpoints.
uint16_t device_id
This endpoint's device ID.
uint8_t device_version
Lower 4 bits are used, upper 4 are reserved and should be 0.
const wpan_cluster_table_entry_t * cluster_table
Pointers to a list of clusters that ends with WPAN_CLUST_ENTRY_LIST_END.
wpan_tick_fn tick
read and dispatch frames
wpan_endpoint_send_fn endpoint_send
send frame to an endpoint
wpan_endpoint_get_next_fn endpoint_get_next
walk endpoint table
wpan_address_t address
IEEE/MAC and network addresses.
uint16_t payload
max bytes in RF payload, need to refresh if encryption enabled/disabled
uint16_t flags
Bitfield describing the device's capabilities (maybe CAN_SLEEP, nodetype, etc.) and state.
const wpan_endpoint_table_entry_t * endpoint_table
Pointer to a table of the device's endpoints, ending with WPAN_ENDPOINT_TABLE_END.
uint8_t transaction_id
void FAR * context
uint16_t timeout
Time to expire conversation (0 for never or lower 16 bits of xbee_seconds_timer) – limited to 9 hours (32,768 seconds).
wpan_response_fn handler
uint8_t last_transaction
wpan_conversation_t conversations [WPAN_MAX_CONVERSATIONS]
ZigBee Stack Profile IDs
4-bit values used in ZigBee beacons
#define WPAN_STACK_PROFILE_PROPRIETARY 0x0
Network Specific.
#define WPAN_STACK_PROFILE_ZIGBEE 0x1
ZigBee (2006)
#define WPAN_STACK_PROFILE_ZIGBEE_PRO 0x2
ZigBee PRO (2007)
Profile IDs
ZigBee Device Object (aka ZigBee Device Profile)
#define WPAN_PROFILE_ZDO 0x0000
#define WPAN_PROFILE_SMART_ENERGY 0x0109
Smart Energy Profile.
#define WPAN_PROFILE_DIGI 0xC105
Digi International, mfg-specific.
Manufacturer IDs
Contact the ZigBee Alliance to have a Manufacturer ID assigned to your company.
DO NOT use the Digi Manufacturer ID for your own manufacturer-specific profiles/clusters/attributes.
#define WPAN_MANUFACTURER_DIGI 0x101E
Digi International (MaxStream)
#define WPAN_MANUFACTURER_DIGI2 0x1087
Digi International.
#define WPAN_MANUFACTURER_TEST1 0xFFF1
Test Vendor #1.
#define WPAN_MANUFACTURER_TEST2 0xFFF2
Test Vendor #2.
#define WPAN_MANUFACTURER_TEST3 0xFFF3
Test Vendor #3.
List of fixed endpoints
ZigBee Device Object/Profile
#define WPAN_ENDPOINT_ZDO 0x00
#define WPAN_ENDPOINT_DIGI_SE 0x5E
Digi Smart Energy.
#define WPAN_ENDPOINT_DDO 0xE6
Digi Device Objects.
#define WPAN_ENDPOINT_DIGI_DEVICE WPAN_ENDPOINT_DDO
#define WPAN_ENDPOINT_DIGI_DATA 0xE8
Digi Data.
#define WPAN_ENDPOINT_BROADCAST 0xFF
Broadcast Endpoint.
Bitfields for flags parameter to a wpan_endpoint_send_fn().
#define WPAN_SEND_FLAG_NONE 0x0000
#define WPAN_SEND_FLAG_ENCRYPTED 0x0001
Values for flags field of wpan_cluster_table_entry_t.
#define WPAN_CLUST_FLAG_NONE 0x00
no flags
#define WPAN_CLUST_FLAG_INPUT 0x01
input/server cluster (typically receives requests)
#define WPAN_CLUST_FLAG_OUTPUT 0x02
output/client cluster (typically receives responses)
#define WPAN_CLUST_FLAG_INOUT 0x03
both client and server cluster
#define WPAN_CLUST_FLAG_SERVER WPAN_CLUST_FLAG_INPUT
alias name for input cluster (uses ZCL terminology)
#define WPAN_CLUST_FLAG_CLIENT WPAN_CLUST_FLAG_OUTPUT
alias name for output cluster (uses ZCL terminology)
#define WPAN_CLUST_FLAG_ENCRYPT 0x10
Data sent or received by this cluster must be encrypted.
#define WPAN_CLUST_FLAG_ENCRYPT_UNICAST 0x20
Unicast data sent or received by this cluster must be encrypted, but unencrypted broadcast frames are OK.
#define WPAN_CLUST_FLAG_NOT_ZCL 0x80
this cluster is NOT using the ZigBee Cluster Library (ZCL)
Detailed Description
Macro Definition Documentation
#define WPAN_CLUST_ENTRY_LIST_END { WPAN_CLUSTER_END_OF_LIST }
Macro for a wpan_cluster_table_entry_t that can be used to mark the end of the table.
#define WPAN_CLUST_FLAG_ENCRYPT 0x10
Data sent or received by this cluster must be encrypted.
Do not accept unencrypted broadcast messages. If using this flag on a non-ZCL cluster, be sure to set WPAN_CLUST_FLAG_NOT_ZCL as well.
Referenced by _pxbee_ota_xmodem_write(), _wpan_endpoint_dispatch(), pxbee_ota_init(), pxbee_ota_server_cmd(), wpan_envelope_reply(), wpan_envelope_send(), and zdo_mgmt_leave_req().
#define WPAN_CLUST_FLAG_ENCRYPT_UNICAST 0x20
Unicast data sent or received by this cluster must be encrypted, but unencrypted broadcast frames are OK.
If using this flag on a non-ZCL cluster, be sure to set WPAN_CLUST_FLAG_NOT_ZCL as well.
Referenced by _wpan_endpoint_dispatch().
#define WPAN_CLUSTER_END_OF_LIST 0xFFFF
Cluster ID used to mark the end of cluster_table in wpan_endpoint_table_entry_t.
Referenced by _match_desc_cluster_list(), _simple_desc_cluster_list(), wpan_cluster_match(), and zcl_time_find_servers().
#define WPAN_DEV_IS_AUTHENTICATED (dev) ((dev)->flags & WPAN_FLAG_AUTHENTICATED)
Macro to test whether a device has authenticated with the trust center.
Parameters
[in] dev (wpan_dev_t FAR *) to test
Return values
0 device has authenticated
!0 device has not authenticated
#define WPAN_DEV_IS_JOINED (dev) ((dev)->flags & WPAN_FLAG_JOINED)
Macro to test whether a device has joined the network.
Parameters
[in] dev (wpan_dev_t FAR *) to test
Return values
0 device has not joined the network
!0 device has joined the network
Referenced by xbee_cmd_init_device().
#define WPAN_ENDPOINT_TABLE_END { WPAN_ENDPOINT_END_OF_LIST }
Macro for a wpan_endpoint_table_entry_t that can be used to mark the end of the table.
#define WPAN_MAX_CONVERSATIONS 3
Number of outstanding requests to track in a wpan_ep_state_t associated with an endpoint.
Referenced by _wpan_endpoint_expire_conversations(), wpan_conversation_register(), and wpan_conversation_response().
Typedef Documentation
typedef int(* _wpan_config_fn) (struct wpan_dev_t *dev,...)
Function called by the WPAN APS layer to configure the underlying network device.
Exact implementation is currently undefined, but this entry exists for future expansion of the API.
Parameters
[in] dev device to configure
... variable arguments to the function
Return values
0 configuration request processed successfully
>0 error parsing parameter #retval
typedef int(* wpan_aps_handler_fn) (const wpan_envelope_t FAR *envelope, void FAR *context)
General handler used in the cluster table.
Dispatcher searches an endpoint's cluster table for a matching cluster, and hands the frame off to the cluster's handler.
If the cluster's handler is set to NULL, or the frame is for a cluster ID that does not appear in the table, the dispatcher hands the frame off to the endpoint's handler.
Parameters
[in] envelope information about the frame (addresses, endpoint, profile, cluster, etc.)
[in,out] context user context (from cluster table)
Return values
0 handled data
!0 some sort of error processing data
typedef const wpan_endpoint_table_entry_t*(* wpan_endpoint_get_next_fn) (struct wpan_dev_t *dev, const wpan_endpoint_table_entry_t *ep)
Custom function for walking the endpoint table.
The application can define its own function to walk the endpoint table, possibly to support a dynamic table or a table where endpoints aren't always visible.
Parameters
[in] dev device with endpoint table to walk
[in] ep NULL to return first entry in table, or a pointer previously returned by this function to get the next entry
Return values
NULL dev is invalid or reached end of table
!NULL next entry from table
See also
wpan_endpoint_match(), wpan_cluster_match(), wpan_endpoint_get_next()
typedef int(* wpan_endpoint_send_fn) (const wpan_envelope_t FAR *envelope, uint16_t flags)
Function called by the WPAN APS layer to send a frame out on the network.
This is part of the glue that links the XBee layer with the WPAN/ZigBee layers.
Parameters
[in] envelope information about the frame (addresses, endpoint, profile, cluster, payload, etc.)
[in] flags flags related to sending, see WPAN_SEND_FLAG_* macros
#WPAN_SEND_FLAG_NONE: no special behavior
#WPAN_SEND_FLAG_ENCRYPTED: use APS layer encryption
Return values
0 frame sent
!0 error sending frame
-EMSGSIZE payload is too large
Todo:
Add support for a broadcast radius? Don't send Tx Status? Use frame ID 0?
Todo:
come up with standard error codes for the following possible errors? outbound frame buffer is full, invalid data in envelope, payload is too big
typedef int(* wpan_ep_handler_fn) (const wpan_envelope_t FAR *envelope, struct wpan_ep_state_t FAR *ep_state)
General handler used in the endpoint table.
If a cluster's handler is set to NULL, or the frame is for a cluster ID that does not appear in the table, the dispatcher hands the frame off to the endpoint's handler.
Parameters
[in] envelope information about the frame (addresses, endpoint, profile, cluster, etc.)
[in,out] ep_state pointer to endpoint state structure
Return values
0 handled data
!0 some sort of error processing data
typedef int(* wpan_response_fn) (struct wpan_conversation_t FAR *conversation, const wpan_envelope_t FAR *envelope)
Handler registered with wpan_conversation_register() to process responses to outstanding requests.
Parameters
[in] conversation Pointer to entry in conversation table. Handler can use the pointer to access the context and transaction ID from the conversation, or request deletion of the conversation via wpan_conversation_delete(). Never NULL.
[in] envelope envelope with response or NULL if there was a timeout
Return values
WPAN_CONVERSATION_END end of conversation, no more responses expected
WPAN_CONVERSATION_CONTINUE leave conversation open, more responses are expected
typedef int(* wpan_tick_fn) (struct wpan_dev_t *dev)
Function called by the WPAN APS layer to have the underlying device read and dispatch frames.
Parameters
[in] dev device to tick
Returns
number of frames processed during the tick
Enumeration Type Documentation
enum wpan_clust_digi
Digi Data cluster IDs (endpoint WPAN_ENDPOINT_DIGI_DATA)
Enumerator
DIGI_CLUST_SLEEP_SYNC
DigiMesh Sleeping Router Sync.
DIGI_CLUST_SERIAL
Serial data.
DIGI_CLUST_LOOPBACK
Serial loopback transmit.
DIGI_CLUST_ND_COMMAND
Digi ND Command.
DIGI_CLUST_DN_COMMAND
Digi DN Command.
DIGI_CLUST_REMOTE_COMMAND
Remote Command Request.
DIGI_CLUST_NR_COMMAND
Digi NR Command.
DIGI_CLUST_IODATA
Unsolicited I/O data sample.
DIGI_CLUST_WATCHPORT
Unsolicited Watchport sensor.
DIGI_CLUST_NODEID_MESSAGE
Node ID Message.
DIGI_CLUST_DN_RESPONSE
Digi DN Response.
DIGI_CLUST_REMOTE_RESPONSE
Digi Remote Command Response.
DIGI_CLUST_NR_RESPONSE
Digi NR Response.
DIGI_CLUST_PROG_XBEE_OTA_UPD
Start OTA update of PXBee App.
DIGI_CLUST_NBRFWUPDATE
Neighbor FW update.
DIGI_CLUST_REMFWUPDATE
Remote FW update.
DIGI_CLUST_FWUPDATERESP
FW update response.
Function Documentation
int _wpan_endpoint_dispatch (wpan_envelope_t * envelope, const wpan_endpoint_table_entry_t * ep)
Dispatch a message for a given endpoint.
Should only be called from wpan_envelope_dispatch.
Looks up the cluster ID in the endpoint's cluster table and passes envelope off to the cluster handler (if a matching cluster was found) or the endpoint handler.
Parameters
[in] envelope structure containing all necessary information about message (endpoints, cluster, profile, etc.)
[in] ep endpoint to dispatch envelope to
Return values
0 successfully dispatched message
-ENOENT no handler for this endpoint/cluster
!0 error dispatching messages
References wpan_envelope_t::cluster_id, wpan_endpoint_table_entry_t::cluster_table, wpan_cluster_table_entry_t::context, wpan_envelope_t::dest_endpoint, ENOENT, wpan_endpoint_table_entry_t::ep_state, FAR, wpan_cluster_table_entry_t::flags, wpan_cluster_table_entry_t::handler, wpan_endpoint_table_entry_t::handler, WPAN_CLUST_FLAG_ENCRYPT, WPAN_CLUST_FLAG_ENCRYPT_UNICAST, WPAN_CLUST_FLAG_INOUT, WPAN_CLUST_FLAG_NOT_ZCL, wpan_cluster_match(), WPAN_ENVELOPE_BROADCAST_ADDR, WPAN_ENVELOPE_RX_APS_ENCRYPT, and zcl_invalid_cluster().
Referenced by wpan_envelope_dispatch().
void _wpan_endpoint_expire_conversations (wpan_ep_state_t FAR * state)
Walk an endpoint's conversation table and expire any conversations that have timed out.
Parameters
[in] state endpoint state (from endpoint table)
References FAR, wpan_conversation_delete(), WPAN_MAX_CONVERSATIONS, and xbee_seconds_timer().
Referenced by wpan_conversation_delete(), and wpan_tick().
const wpan_cluster_table_entry_t * wpan_cluster_match (uint16_t match, uint8_t mask, const wpan_cluster_table_entry_t * entry)
Search a cluster table for a matching cluster ID.
Parameters
[in] match ID to match
[in] mask Flags to match against the flags member of the wpan_cluster_table_entry_t structure. If any flags match, the entry is returned. Typically one of
WPAN_CLUST_FLAG_INPUT (or WPAN_CLUST_FLAG_SERVER)
WPAN_CLUST_FLAG_OUTPUT (or WPAN_CLUST_FLAG_CLIENT)
[in] entry pointer to list of entries to search
Return values
NULL entry is invalid or search reached WPAN_CLUSTER_END_OF_LIST without finding a match.
!NULL Pointer to matching entry from table.
See also
wpan_endpoint_get_next(), wpan_endpoint_match()
References wpan_cluster_table_entry_t::cluster_id, wpan_cluster_table_entry_t::flags, and WPAN_CLUSTER_END_OF_LIST.
Referenced by _wpan_endpoint_dispatch(), _zcl_send_read_from_zdo_match(), _zdo_match_desc_respond(), and wpan_endpoint_of_cluster().
void wpan_conversation_delete (wpan_conversation_t FAR * conversation)
Delete a conversation from an endpoint's conversation table.
Parameters
[in,out] conversation conversation to delete
References _wpan_endpoint_expire_conversations(), and FAR.
Referenced by _wpan_endpoint_expire_conversations(), and wpan_conversation_response().
int wpan_conversation_register (wpan_ep_state_t FAR * state, wpan_response_fn handler, const void FAR * context, uint16_t timeout)
Add a conversation to the table of tracked conversations.
Parameters
[in,out] state endpoint state associated with sending endpoint
[in] handler handler to call when responses come back, or NULL to increment and return the endpoint's transaction ID
[in] context pointer stored in conversation table and passed to callback handler
[in] timeout number of seconds before generating timeout, or 0 for none
Return values
0-255 transaction ID to use in sent frame
-EINVAL state is invalid (NULL)
-ENOSPC table is full
See also
wpan_endpoint_next_trans
References EINVAL, ENOSPC, FAR, WPAN_MAX_CONVERSATIONS, and xbee_seconds_timer().
Referenced by zdo_send_bind_req(), zdo_send_descriptor_req(), zdo_send_ieee_addr_req(), zdo_send_match_desc(), zdo_send_nwk_addr_req(), and zdo_simple_desc_request().
int wpan_conversation_response (wpan_ep_state_t FAR * state, uint8_t transaction_id, const wpan_envelope_t FAR * envelope)
Searches the endpoint's table of active conversations (outstanding requests waiting for responses) for a given transaction.
Hands the response frame off to the handler registered to the conversation with wpan_conversation_register().
Parameters
[in] state endpoint state (from endpoint table) or NULL to look it up using the envelope
[in] transaction_id transaction ID from frame payload, used to look up conversation
[in] envelope envelope from response frame, passed to conversation's handler
Return values
-EINVAL invalid parameter passed to function, or conversation not found in table
0 handler processed response
!0 handler reported an error while processing response
References EINVAL, wpan_endpoint_table_entry_t::ep_state, FAR, wpan_conversation_delete(), wpan_endpoint_match(), and WPAN_MAX_CONVERSATIONS.
Referenced by zcl_general_command(), and zdo_handler().
const wpan_endpoint_table_entry_t * wpan_endpoint_get_next (wpan_dev_t * dev, const wpan_endpoint_table_entry_t * ep)
Function used to walk a device's endpoint table.
For most devices, this will just walk the entries in dev->endpoint_table. For custom applications a function may dynamically return entries.
Use of this function is the only way to walk the endpoint table.
Parameters
[in] dev device with endpoint table to walk
[in] ep NULL to return first entry in table, or a pointer previously returned by this function to get the next entry
Return values
NULL dev is invalid or reached end of table
!NULL next entry from table
See also
wpan_endpoint_match(), wpan_cluster_match()
References wpan_endpoint_table_entry_t::endpoint, wpan_dev_t::endpoint_get_next, wpan_dev_t::endpoint_table, and WPAN_ENDPOINT_END_OF_LIST.
Referenced by _zdo_active_ep_respond(), _zdo_match_desc_respond(), wpan_endpoint_match(), wpan_endpoint_of_cluster(), wpan_envelope_dispatch(), and wpan_tick().
const wpan_endpoint_table_entry_t * wpan_endpoint_match (wpan_dev_t * dev, uint8_t endpoint, uint16_t profile_id)
Walk a device's endpoint table looking for a matching endpoint ID and profile ID.
Used by the endpoint dispatcher and ZDO layer to describe available endpoints on this device.
Parameters
[in] dev Device with endpoint table to search.
[in] endpoint Endpoint number to search for.
[in] profile_id Profile to match or WPAN_APS_PROFILE_ANY to search on endpoint number only.
Return values
NULL dev is invalid or reached end of table without finding a match
!NULL next entry from table
See also
wpan_endpoint_of_cluster(), wpan_endpoint_get_next(), wpan_cluster_match(), wpan_endpoint_of_envelope()
References wpan_endpoint_table_entry_t::endpoint, wpan_endpoint_table_entry_t::profile_id, and wpan_endpoint_get_next().
Referenced by _zdo_endpoint_of(), _zdo_simple_desc_respond(), wpan_conversation_response(), wpan_endpoint_of_envelope(), and wpan_envelope_dispatch().
uint8_t wpan_endpoint_next_trans (const wpan_endpoint_table_entry_t * ep)
Increment and return the endpoint's transaction ID counter.
Parameters
[in] ep entry from endpoint table
Return values
0-255 current transaction ID for endpoint
References wpan_endpoint_table_entry_t::ep_state.
Referenced by _zcl_comm_command_build(), zcl_client_read_attributes(), zcl_ota_upgrade_image_notify(), zcl_send_write_attributes(), and zdo_mgmt_leave_req().
const wpan_endpoint_table_entry_t * wpan_endpoint_of_cluster (wpan_dev_t * dev, uint16_t profile_id, uint16_t cluster_id, uint8_t mask)
Walk a device's endpoint table looking for a matching profile ID and cluster ID.
Used to find the correct endpoint to use for sending ZCL client requests.
Parameters
[in] dev Device with endpoint table to search.
[in] profile_id Profile to match or WPAN_APS_PROFILE_ANY to search on cluster ID only.
[in] cluster_id Cluster ID to search for.
[in] mask Flags to match against the flags member of the wpan_cluster_table_entry_t structure. If any flags match, the entry is returned. Typically one of
WPAN_CLUST_FLAG_INPUT (or WPAN_CLUST_FLAG_SERVER)
WPAN_CLUST_FLAG_OUTPUT (or WPAN_CLUST_FLAG_CLIENT)
Return values
NULL dev is invalid or reached end of table without finding a match
!NULL matching entry from table
See also
wpan_endpoint_match(), wpan_endpoint_get_next(), wpan_cluster_match()
References wpan_endpoint_table_entry_t::cluster_table, wpan_endpoint_table_entry_t::endpoint, wpan_endpoint_table_entry_t::profile_id, wpan_cluster_match(), and wpan_endpoint_get_next().
Referenced by _zcl_comm_command_build(), and zcl_time_find_servers().
const wpan_endpoint_table_entry_t * wpan_endpoint_of_envelope (const wpan_envelope_t * env)
Look up the endpoint table entry for the source endpoint of an envelope.
Parameters
[in] env Envelope for lookup. Uses env->source_endpoint and env->profile_id to find the endpoint table entry for env->dev.
Return values
NULL invalid parameter, or reached end of table without finding a match
!NULL entry from table
See also
wpan_endpoint_of_cluster(), wpan_endpoint_get_next(), wpan_cluster_match(), wpan_endpoint_match()
References wpan_envelope_t::dev, wpan_envelope_t::profile_id, wpan_envelope_t::source_endpoint, and wpan_endpoint_match().
Referenced by _zcl_comm_command_build(), and zcl_send_write_attributes().
void wpan_envelope_create (wpan_envelope_t * envelope, wpan_dev_t * dev, const addr64 FAR * ieee, uint16_t network_addr)
Starting with a blank envelope, fill in the device, 64-bit IEEE address and 16-bit network address of the destination.
The profile ID, cluster ID, source/destination endpoints and envelope options are all be set to zero.
Parameters
[out] envelope envelope to populate
[in] dev device that will send this envelope
[in] ieee 64-bit IEEE/MAC address of recipient or one of
WPAN_IEEE_ADDR_COORDINATOR (send to coordinator)
WPAN_IEEE_ADDR_BROADCAST (broadcast packet)
WPAN_IEEE_ADDR_UNDEFINED (use network address only)
[in] network_addr 16-bit network address of recipient or one of
WPAN_NET_ADDR_COORDINATOR for the coordinator (use the coordinator's actual IEEE address for the ieee parameter).
WPAN_NET_ADDR_BCAST_ALL_NODES (broadcast to all nodes)
WPAN_NET_ADDR_BCAST_NOT_ASLEEP (broadcast to awake nodes)
WPAN_NET_ADDR_BCAST_ROUTERS (broadcast to routers/coordinator)
WPAN_NET_ADDR_UNDEFINED (use 64-bit address only)
When sending broadcast packets, use WPAN_IEEE_ADDR_BROADCAST and WPAN_NET_ADDR_UNDEFINED. Don't set both addresses to broadcast.
When using DigiMesh protocol, always set the network_addr to WPAN_NET_ADDR_UNDEFINED.
See also
wpan_envelope_reply()
References wpan_envelope_t::dev, wpan_envelope_t::ieee_address, and wpan_envelope_t::network_address.
Referenced by _pxbee_ota_xmodem_write(), _zdo_envelope_create(), pxbee_ota_init(), zcl_ota_upgrade_image_notify(), and zdo_send_ieee_addr_req().
int wpan_envelope_dispatch (wpan_envelope_t * envelope)
Find the matching endpoint for the provided envelope and have it process the frame.
In the case of the broadcast endpoint (255), dispatches the frame to all endpoints matching the envelope's profile ID.
Looks up the destination endpoint and cluster ID in the device's endpoint table and passes envelope off to the cluster handler (if a matching cluster was found) or the endpoint handler.
Parameters
[in] envelope structure containing all necessary information about message (endpoints, cluster, profile, etc.)
Return values
0 successfully dispatched message
-ENOENT no handler for this endpoint/cluster
!0 error dispatching messages
References _wpan_endpoint_dispatch(), wpan_envelope_t::dest_endpoint, wpan_envelope_t::dev, wpan_endpoint_table_entry_t::endpoint, ENOENT, wpan_envelope_t::profile_id, wpan_endpoint_table_entry_t::profile_id, WPAN_ENDPOINT_BROADCAST, wpan_endpoint_get_next(), wpan_endpoint_match(), WPAN_ENVELOPE_BROADCAST_EP, WPAN_ENVELOPE_CLUSTER_FLAGS, and wpan_envelope_dump().
Referenced by _xbee_handle_receive_explicit().
void wpan_envelope_dump (const wpan_envelope_t FAR * envelope)
Debugging function to dump the contents of an envelope to stdout.
Displays all fields from the envelope, plus the contents of the payload
Parameters
[in] envelope envelope to dump
References addr64_format(), ADDR64_STRING_LENGTH, hex_dump(), HEX_DUMP_FLAG_OFFSET, and PRIsFAR.
Referenced by wpan_envelope_dispatch(), wpan_envelope_send(), zcl_client_read_attributes(), zcl_send_response(), zcl_send_write_attributes(), and zdo_send_match_desc().
int wpan_envelope_reply (wpan_envelope_t FAR * reply, const wpan_envelope_t FAR * original)
Create a reply envelope based on the envelope received from a remote node.
Copies the interface, addresses, profile and cluster from the original envelope, and then swaps the source and destination endpoints.
Note that it may be necessary for the caller to change the cluster_id as well, after building the reply envelope. For example, ZDO responses set the high bit of the request's cluster ID.
Parameters
[out] reply Buffer for storing the reply envelope.
[in] original Original envelope, received from a remote node, to base the reply on.
Return values
0 addressed reply envelope
-EINVAL either parameter is NULL or they point to the same address
See also
wpan_envelope_create()
References EINVAL, WPAN_CLUST_FLAG_ENCRYPT, and WPAN_ENVELOPE_RX_APS_ENCRYPT.
Referenced by _zcl_send_read_from_zdo_match(), pxbee_ota_server_cmd(), zcl_comm_response(), zcl_send_response(), and zdo_send_response().
int wpan_envelope_send (const wpan_envelope_t FAR * envelope)
Send a message to an endpoint using address and payload information stored in a wpan_envelope_t structure.
Parameters
[in] envelope envelope of request to send
Return values
0 request sent
!0 error trying to send request
References EINVAL, WPAN_CLUST_FLAG_ENCRYPT, and wpan_envelope_dump().
Referenced by _zcl_comm_command_send(), pxbee_ota_init(), pxbee_ota_server_cmd(), xbee_transparent_serial(), zcl_client_read_attributes(), zcl_comm_response(), zcl_ota_upgrade_image_notify(), zcl_send_response(), zcl_send_write_attributes(), zdo_mgmt_leave_req(), zdo_send_bind_req(), zdo_send_descriptor_req(), zdo_send_ieee_addr_req(), zdo_send_match_desc(), zdo_send_nwk_addr_req(), zdo_send_response(), and zdo_simple_desc_request().
int wpan_tick (wpan_dev_t * dev)
Calls the underlying hardware tick function to process received frames, and times out expired conversations.
Parameters
[in] dev WPAN device to tick
Return values
>=0 number of frames processed during the tick
-EINVAL device does not have a tick function assigned to it
<0 some other error encountered during the tick
References _wpan_endpoint_expire_conversations(), EINVAL, wpan_endpoint_table_entry_t::ep_state, wpan_dev_t::tick, and wpan_endpoint_get_next().
Referenced by _sxa_io_process_response().
Variable Documentation
uint16_t cluster_id
16-bit cluster id, in host byte order.
WPAN_CLUSTER_END_OF_LIST (0xFFFF) marks the end of the list. Clusters 0x0000 to 0x7FFF are Standard ZigBee clusters, 0x8000 to 0xFBFF are reserved and 0xFC00 to 0xFFFF are manufacturer-specific (with a standard ZigBee profile).
Referenced by _simple_desc_cluster_list(), and wpan_cluster_match().
const wpan_cluster_table_entry_t* cluster_table
Pointers to a list of clusters that ends with WPAN_CLUST_ENTRY_LIST_END.
Maximum of 255 input and 255 output clusters (Simple Descriptor uses 8-bit fields for input cluster count and output cluster count).
Referenced by _wpan_endpoint_dispatch(), _zdo_match_desc_respond(), _zdo_simple_desc_respond(), and wpan_endpoint_of_cluster().
const void FAR* context
Declared const so initializers can use const or non-const pointers.
The const is discarded before passing the context on to wpan_aps_handler_fn(). For a ZCL endpoint, context points to an attribute tree (zcl_attribute_tree_t).
Referenced by _wpan_endpoint_dispatch().
const wpan_endpoint_table_entry_t* endpoint_table
Pointer to a table of the device's endpoints, ending with WPAN_ENDPOINT_TABLE_END.
Do not reference directly! Use wpan_endpoint_get_next() to walk the table.
Referenced by wpan_endpoint_get_next(), and xbee_wpan_init().
struct wpan_ep_state_t FAR* ep_state
Structure used to track transactions and conversations on ZDO/ZDP and ZCL endpoints.
Should be NULL for other types of endpoints.
Referenced by _wpan_endpoint_dispatch(), wpan_conversation_response(), wpan_endpoint_next_trans(), wpan_tick(), and zdo_endpoint_state().
uint16_t flags
Bitfield describing the device's capabilities (maybe CAN_SLEEP, nodetype, etc.) and state.
Only valid if xbee_cmd_init_device() is used or ALL Modem Status messages are received from radio. User code should not access this directly, but use WPAN_DEV_IS_* macros instead.
Referenced by _xbee_dev_modem_status().
wpan_aps_handler_fn handler
Function to receive all frames for this cluster, or NULL to have endpoint's handler process the frame.
Referenced by _wpan_endpoint_dispatch().
wpan_ep_handler_fn handler
Function to receive all frames for invalid clusters, or clusters with a NULL handler.
Referenced by _wpan_endpoint_dispatch().
uint16_t profile_id
This endpoint's profile ID.
See WPAN_PROFILE_* macros for some known profile IDs.
Referenced by _zcl_comm_command_build(), _zdo_match_desc_respond(), _zdo_simple_desc_respond(), wpan_endpoint_match(), wpan_endpoint_of_cluster(), wpan_envelope_dispatch(), and zcl_ota_upgrade_image_notify().
uint16_t timeout
Time to expire conversation (0 for never or lower 16 bits of xbee_seconds_timer) – limited to 9 hours (32,768 seconds).
We could save another byte if it's ok to limit to 2 minutes and we'll check for expirations at least every 7 seconds.